server:
  address: 0.0.0.0
  port: 8886

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yunqi_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: yunqi_db
    password: ezDe6

    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: LOWER_CASE
    default-property-inclusion: NON_NULL